# Generated by Django 4.2.5 on 2023-10-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_submission_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='maximum_points',
            new_name='points',
        ),
    ]
