# Generated by Django 4.2.5 on 2023-10-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_rename_maximum_points_assignment_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
