# Generated by Django 4.2.4 on 2023-11-18 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grades.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0004_alter_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[grades.models.valid_float]),
        ),
    ]
