# Generated by Django 4.2.4 on 2023-11-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_submission_grader_alter_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
